export const WSURL = "wss://multiplayer-typing-backend.onrender.com/"
export const INIT = "init_game"
export const PROGRESS = "progress_game"
export const OTHERPLAYERLEFT= "otherplayerleft"
export const GAMEOVER = "game_over"
